# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProteoformWarehouse(object):
    def setupUi(self, ProteoformWarehouse):
        ProteoformWarehouse.setObjectName("ProteoformWarehouse")
        ProteoformWarehouse.resize(800, 600)
        self.verticalLayoutWidget = QtWidgets.QWidget(ProteoformWarehouse)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(60, 50, 351, 311))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listWidget = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.listWidget.addItem(item)
        self.verticalLayout.addWidget(self.listWidget)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.deleteAccession = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.deleteAccession.setObjectName("deleteAccession")
        self.gridLayout.addWidget(self.deleteAccession, 2, 1, 1, 1)
        self.addAccession = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.addAccession.setObjectName("addAccession")
        self.gridLayout.addWidget(self.addAccession, 2, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(ProteoformWarehouse)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(430, 140, 314, 116))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.inputFileButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.inputFileButton.setObjectName("inputFileButton")
        self.verticalLayout_2.addWidget(self.inputFileButton)
        self.allAccessionGenerate = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.allAccessionGenerate.setObjectName("allAccessionGenerate")
        self.verticalLayout_2.addWidget(self.allAccessionGenerate)
        self.selectAccessionGenerate = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.selectAccessionGenerate.setObjectName("selectAccessionGenerate")
        self.verticalLayout_2.addWidget(self.selectAccessionGenerate)
        self.selectAccessionGenerate.raise_()
        self.allAccessionGenerate.raise_()
        self.inputFileButton.raise_()
        self.gridLayoutWidget_3 = QtWidgets.QWidget(ProteoformWarehouse)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(60, 12, 671, 31))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.filenamebox = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.filenamebox.setText("")
        self.filenamebox.setReadOnly(False)
        self.filenamebox.setObjectName("filenamebox")
        self.gridLayout_3.addWidget(self.filenamebox, 0, 1, 1, 1)
        self.label.setBuddy(self.filenamebox)

        self.retranslateUi(ProteoformWarehouse)
        QtCore.QMetaObject.connectSlotsByName(ProteoformWarehouse)

    def retranslateUi(self, ProteoformWarehouse):
        _translate = QtCore.QCoreApplication.translate
        ProteoformWarehouse.setWindowTitle(_translate("ProteoformWarehouse", "ProteoformWarehouse"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("ProteoformWarehouse", "Accession Numbers:"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.deleteAccession.setText(_translate("ProteoformWarehouse", "Delete Accesion Row"))
        self.addAccession.setText(_translate("ProteoformWarehouse", "Add Accession Row"))
        self.inputFileButton.setText(_translate("ProteoformWarehouse", "Select Input File"))
        self.allAccessionGenerate.setText(_translate("ProteoformWarehouse", "Generate XML Files for ALL Accessions in File"))
        self.selectAccessionGenerate.setText(_translate("ProteoformWarehouse", "Generate XML Files for Accessions in Table"))
        self.label.setText(_translate("ProteoformWarehouse", "Input File Name:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ProteoformWarehouse = QtWidgets.QWidget()
    ui = Ui_ProteoformWarehouse()
    ui.setupUi(ProteoformWarehouse)
    ProteoformWarehouse.show()
    sys.exit(app.exec_())
